### ISSUE TITLE
Test infrastructure should initialize output buffers with a default value.

### ISSUE THREAD

**Issue by matthew-pickett** [opveclib/opveclib#3]
A common mistake when writing operators is that not all elements in the output(s) are actually set by the operator. When output buffers are allocated without initialization this error can be difficult to see without more extensive debugging. The test infrastructure should default to initializing all elements of all outputs to a standard value so this is easier to detect.

Perhaps the maximum value for each output data type should be used? This avoids using zeros as the default output which could be accidentally correct in a lot of cases.

**Comment by kbrems** [comment]
Fixed. All output tensors are initialized to byte value of 0xFE in testcudaop.cc and testcop.cc
