### ISSUE TITLE
Enable special values (e.g. infinity) for all data types

### ISSUE THREAD

**Issue by matthew-pickett** [opveclib/opveclib#4]
The expression API currently does not have an abstraction for the special values of the various data types. These special values include:  +infinity, -infinity, nan, min value, max value, epsilon.

Are there any others that need to be included?

**Comment by kbrems** [comment]
added functions for isinf, isfinite and isnan to unary math, following the numpy standard.

**Comment by kbrems** [comment]
added limits branch with implementation for max, min and eps implementation, but it does not work in an operator.

**Comment by kbrems** [comment]
fixed max, min and eps implementations.
